OBS_FOLDER = '/projects/0/lotaas2/data/out/'
RAW_FOLDER = '/projects/0/lotaas2/data/raw/'
SITE_CERT = '/projects/0/lotaas2/software/LSP/.site_cert.json'
WRK_FOLDER = '/dev/shm/wrk/{}'
TMP_FOLDER = '/dev/shm/tmp/{}'
MASK_FILE = OBS_FOLDER + '{idL}/SAP{sap}/{idL}_SAP{sap}_BEAM{beam}/{idL}_SAP{sap}_BEAM{beam}_rfifind.mask'