OBS_FOLDER = '/projects/0/lotaas/data/out' + '/'
RAW_FOLDER = '/projects/0/lotaas/data/raw' + '/'
SITE_CERT = '/projects/0/lotaas/software/LSP/.site_cert.json'
TEMP_FOLDER = '/dev/shm/tmp/{}'
MASK_FILE = OBS_FOLDER + '{idL}/SAP{sap}/{idL}_SAP{sap}_BEAM{beam}/{idL}_SAP{sap}_BEAM{beam}_rfifind.mask'