OBS_FOLDER = '/projects/0/lotaas2/data/out/'
RAW_FOLDER = '/projects/0/lotaas2/data/raw/'
SITE_CERT = '/projects/0/lotaas2/software/LSP/.site_cert.json'
WRK_FOLDER = '/dev/shm/wrk/{}'
TMP_FOLDER = '/dev/shm/tmp/{}'
MASK_FILE = RAW_FOLDER + '{idL}_red/SAP{sap}/BEAM{beam}/{idL}_SAP{sap}_BEAM{beam}_rfifind.mask'
MODEL_FILE = '/projects/0/lotaas2/software/LSP/ML_model_v1.model'